pipelines:
  branches:
    master:
      - step:
          name: Build and Push Docker Image
          script:
            - echo $DOCKERHUB_PASSWORD | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            - IMAGE_NAME="${DOCKERHUB_NAMESPACE}/mcrm"
            - docker build -t $IMAGE_NAME:latest .
            - docker push $IMAGE_NAME:latest
          services:
            - docker
