export const crmRoutes = {
  DASHBOARD: "/dashboard",
  CRM_PATH: "/crm",
  HOME_PATH: "",
  LEADS_PATH: "leads",
  LOADS_PATH: "loads",
  GRA_PATH: "gra",
  CONTACTS_PATH: "contacts",
  ACCOUNTS_PATH: "accounts",
  USER_PROFILE_PATH : "profile",
  DEALS_PATH: "deals",
  TASKS_PATH: "tasks",
  REPORTS_PATH: "reports",
  FILTERED_REPORTS_PATH: "filtered-reports",
  ANALYTICS_PATH: "analytics",
  PRODUCTS_PATH: "products",
  ASSETS_PATH: "assets",
  QUOTES_PATH: "quotes",
  SALES_ORDERS_PATH: "sales-orders",
  PURCHASE_ORDERS_PATH: "purchase-orders",
  PAYMENT_ORDERS_PATH: "payment-orders",
  DISPATCH_ORDERS_PATH: "dispatch-orders",
  WORK_ORDERS_PATH: "work-orders",
  INVOICES_PATH: "invoices",
  VENDORS_PATH: "vendors",
  SUPPLIERS_PATH: "suppliers",
  PROJECTS_PATH: "projects",
  ASSET_RECYCLE_REPORT_PATH: 'asset-recycle-report',
  TIME_SHEET_PATH: 'time-sheets',
};

export const sideBarRoutes = {
  BUSINESS_DASHBOARD_PATH: "business-dashboard",
  ANALYTICS_DASHBOARD_PATH: "analytics-dashboard",
  ORDERS_PATH: "orders",
  INVENTORY_PATH: "inventory",
  CUSTOMERS_PATH: "customers",
  CALENDAR_EVENTS_PATH: "calendar-events",
};

export const otherRoutes = {
  LOGIN: "/login",
  SIGNUP: "/signup",
  ABOUT_US: "/about-us",
  PRIVACY_POLICY: "/privacy-policy",
  TERMS: "/terms",
  PRODUCT_PAGE: "/product",
  PRICING_PAGE: "/pricing",
  PLATFORM_PAGE: "/plaform",
  PARTNERS_PAGE: "/partners",
  RESOURCES_PAGE: "/resources",
  COMPANY_PAGE: "/company",
  CONTACT_US_PAGE:"/contact-us",
  LANDING_PAGE: "/*",
};
