// import { Box } from "@mui/material";

// import DatePicker from "common/input/DatePicker";

// const commonColumnProps = {
//   flex: 1,
//   minWidth: 100,
//   editable: false,
//   headerAlign: 'left',
//   align: 'left',
// };

// const dateCell = () => ({
//   type: 'date',
//   valueGetter: ({ value }) => value && new Date(value),
//   renderEditCell: (props) => {
//     const { id, value, field, api } = props;

//     const handleDateChange = (newValue) => {
//       api.setEditCellValue({ id, field, value: newValue });
//     };
//     return <DatePicker {...props} onChange={handleDateChange} />
//   }
// });

// export const detailColumn = (props = {}) => {
//   const {
//     makes,
//     models,
//     itemTypes,
//     projects,
//     loads,
//     warehouses,
//     locations,
//     assetStatus,
//     workOrderList,
//     saleOrderStatuses,
//     saleOrderTypes,
//   } = props;

//   return {
//     leads: [
//       { field: 'leadId', headerName: 'lead ID', ...commonColumnProps, editable: false},
//       { field: 'leadOwner', headerName: 'Lead owner', ...commonColumnProps },
//       { field: 'leadName', headerName: 'Lead name', ...commonColumnProps },
//       {
//         field: 'leadStatus',
//         headerName: 'Lead status',
//         ...commonColumnProps,
//         type: 'singleSelect',
//         valueOptions: ['On Going', 'In Progress', 'Completed'],
//       },
//       { field: 'salutation', headerName: 'Salutation', ...commonColumnProps },
//       { field: 'firstName', headerName: 'First name', ...commonColumnProps },
//       { field: 'lastName', headerName: 'Last name', ...commonColumnProps },
//       { field: 'title', headerName: 'Title', ...commonColumnProps },
//       {
//         field: 'email',
//         headerName: 'Email',
//         flex: 1,
//         minWidth: 200,
//         editable: true,
//       },
//       {
//         field: 'phone',
//         headerName: 'Phone',
//         ...commonColumnProps,
//         minWidth: 150,
//         type: 'number',
//       },
//       { field: 'company', headerName: 'Company', ...commonColumnProps },
//       { field: 'website', headerName: 'Website', ...commonColumnProps },
//     ],

//     loads: [
//       // { field: 'loadId', headerName: 'Load ID', ...commonColumnProps, editable: false },
//       { field: 'loadNo', headerName: 'Load Number', ...commonColumnProps, editable: false  },
//       {
//         field: 'loadStatus',
//         headerName: 'Status',
//         cellClassName: 'status',
//         ...commonColumnProps,
//         type: 'singleSelect',
//         valueOptions: [
//           'New',
//           'Approved',
//           'Active',
//           'Rejected',
//           'Closed',
//         ],
//       },
//       {
//         field: 'project',
//         headerName: 'Project',
//         ...commonColumnProps,
//         type: 'singleSelect',
//         valueOptions: projects,
//       },
//       {
//         field: 'workorder',
//         headerName: 'Work Order',
//         ...commonColumnProps,
//         type: 'singleSelect',
//         valueOptions: workOrderList,
//       },
//       {
//         field: 'receivingUser',
//         headerName: 'Receiving User',
//         ...commonColumnProps,
//         editable: false,
//       },
//       { field: 'clientPO', headerName: 'Client PO', ...commonColumnProps },
//       { field: 'clientRef', headerName: 'Client Ref', ...commonColumnProps },
//       { field: 'inventory', headerName: 'Inventory', ...commonColumnProps },
//       // { field: 'connote', headerName: 'connote', ...commonColumnProps },
//       // {
//       //   field: 'leasingCustomerName',
//       //   headerName: 'Customer',
//       //   ...commonColumnProps,
//       // },
//       {
//         field: 'warehouse',
//         headerName: 'Warehouse',
//         ...commonColumnProps,
//         type: 'singleSelect',
//         valueOptions: warehouses,
//       },
//       {
//         field: 'qty',
//         headerName: 'Qty',
//         ...commonColumnProps,
//         type: 'number',
//       },
//       {
//         field: 'loadTotal',
//         headerName: 'LoadTotal',
//         ...commonColumnProps,
//         type: 'number',
//       },
//       { field: 'graDate', headerName: 'GRA Date', ...commonColumnProps, ...dateCell() },
//       { field: 'dateReceived', headerName: 'Received Date', ...commonColumnProps, ...dateCell() },
//     ],

//     contacts: [
//       { field: 'firstName', headerName: 'First name', ...commonColumnProps },
//       { field: 'lastName', headerName: 'Last name', ...commonColumnProps },
//       { field: 'salutation', headerName: 'Salutation', ...commonColumnProps },
//       {
//         field: 'title',
//         headerName: 'Title',
//         flex: 1,
//         minWidth: 200,
//         editable: true,
//       },
//       {
//         field: 'email',
//         headerName: 'Email',
//         flex: 1,
//         minWidth: 200,
//         editable: true,
//       },
//       {
//         field: 'mobile',
//         headerName: 'Mobile',
//         ...commonColumnProps,
//         type: 'number',
//       },
//       { field: 'company', headerName: 'Company', ...commonColumnProps },
//     ],
//     products: [
//       //{ field: 'id', headerName: 'ID', width: 20},
//       {
//         field: 'productId',
//         headerName: 'productId',
//         ...commonColumnProps,
//         type: 'number',
//       },
//       { field: 'productcode', headerName: 'productcode', ...commonColumnProps },
//       { field: 'productName', headerName: 'productName', ...commonColumnProps },
//       {
//         field: 'productowner',
//         headerName: 'productowner',
//         ...commonColumnProps,
//       },
//       {
//         field: 'productCategory',
//         headerName: 'productCategory',
//         ...commonColumnProps,
//         editable: true,
//       },
//       {
//         field: 'productManufacturer',
//         headerName: 'productManufacturer',
//         ...commonColumnProps,
//         editable: true,
//       },
//       { field: 'vendorName', headerName: 'vendorName', ...commonColumnProps },
//       {
//         field: 'productDescription',
//         headerName: 'productDescription',
//         ...commonColumnProps,
//       },
//       {
//         field: 'productSaleStartDate',
//         headerName: 'productSaleStartDate',
//         ...commonColumnProps,
//         ...dateCell(),
//       },
//       {
//         field: 'productSaleEndDate',
//         headerName: 'productSaleEndDate',
//         ...commonColumnProps,
//         ...dateCell(),
//       },
//       {
//         field: 'productSupportStartDate',
//         headerName: 'productSupportStartDate',
//         ...commonColumnProps,
//         ...dateCell(),
//       },
//       {
//         field: 'productSupportEndDate',
//         headerName: 'productSupportEndDate',
//         ...commonColumnProps,
//         ...dateCell(),
//       },
//       {
//         field: 'productUnitPrice',
//         headerName: 'productUnitPrice',
//         ...commonColumnProps,
//         type: 'number',
//       },
//       {
//         field: 'productCommissionRate',
//         headerName: 'productCommissionRate',
//         ...commonColumnProps,
//         type: 'number',
//       },
//       {
//         field: 'isTaxable',
//         headerName: 'isTaxable',
//         ...commonColumnProps,
//         type: 'boolean',
//       },
//       {
//         field: 'productQuantity',
//         headerName: 'productQuantity',
//         ...commonColumnProps,
//         type: 'number',
//       },
//       {
//         field: 'productQuantityInStock',
//         headerName: 'productQuantityInStock',
//         ...commonColumnProps,
//         type: 'number',
//       },
//       {
//         field: 'productQuantityOrdered',
//         headerName: 'productQuantityOrdered',
//         ...commonColumnProps,
//         type: 'number',
//       },
//       {
//         field: 'productQuantityRecorderLevel',
//         headerName: 'productQuantityRecorderLevel',
//         ...commonColumnProps,
//       },
//       {
//         field: 'productQuantityInDemand',
//         headerName: 'productQuantityInDemand',
//         ...commonColumnProps,
//         type: 'number',
//       },
//       {
//         field: 'isProductActive',
//         headerName: 'isProductActive',
//         ...commonColumnProps,
//         type: 'boolean',
//       },
//     ],
//     assets: [
//       //{ field: 'id', headerName: 'ID', width: 20},
//       {
//         field: 'ssn',
//         headerName: 'SSN',
//         ...commonColumnProps,
//         type: 'number',
//       },
//       {
//         field: 'make',
//         headerName: 'Make',
//         ...commonColumnProps,
//         type: 'singleSelect',
//         valueOptions: makes,
//       },
//       {
//         field: 'model',
//         headerName: 'Model',
//         ...commonColumnProps,
//         type: 'singleSelect',
//         valueOptions: models,
//       },
//       { field: 'serialNo', headerName: 'Serial No', ...commonColumnProps },
//       { field: 'barcode', headerName: 'Barcode', ...commonColumnProps },
//       { field: 'clientRef', headerName: 'ClientRef', ...commonColumnProps },
//       {
//         field: 'clientAssetTag',
//         headerName: 'Client Asset Tag',
//         ...commonColumnProps,
//       },
//       // { field: 'subGrade', headerName: 'subGrade', ...commonColumnProps },
//       // { field: 'reservationCode', headerName: 'reservationCode', ...commonColumnProps },
//       // { field: 'reservationDate', headerName: 'reservationDate', ...commonColumnProps, ...dateCell() },
//       // { field: 'reservationComment', headerName: 'reservationComment', ...commonColumnProps },
//       // { field: 'recycle', headerName: 'recycle', ...commonColumnProps, type: 'boolean' },
//       // { field: 'releaseDate', headerName: 'releaseDate', ...commonColumnProps, ...dateCell() },
//       // { field: 'completeness', headerName: 'completeness', ...commonColumnProps },
//       // { field: 'appearance', headerName: 'appearance', ...commonColumnProps },
//       // { field: 'services', headerName: 'services', ...commonColumnProps },
//       // { field: 'operability', headerName: 'operability', ...commonColumnProps },
//       // { field: 'qtyOnHand', headerName: 'qtyOnHand', ...commonColumnProps, type: 'number' },
//       // { field: 'isSerialised', headerName: 'isSerialised', ...commonColumnProps, type: 'boolean' },
//       // { field: 'physicalInspectionDate', headerName: 'physicalInspectionDate', ...commonColumnProps, ...dateCell() },
//       // { field: 'physicalInspectionUser', headerName: 'physicalInspectionUser', ...commonColumnProps },
//       {
//         field: 'itemType',
//         headerName: 'ItemType',
//         ...commonColumnProps,
//         type: 'singleSelect',
//         valueOptions: itemTypes,
//       },
//       {
//         field: 'assetStatus',
//         headerName: 'Status',
//         cellClassName: 'status',
//         ...commonColumnProps,
//         type: 'singleSelect',
//         valueOptions: assetStatus,
//       },
//       {
//         field: 'buyPrice',
//         headerName: 'Buy Price',
//         ...commonColumnProps,
//         type: 'number',
//       },
//       {
//         field: 'sellPrice',
//         headerName: 'sell Price',
//         ...commonColumnProps,
//         type: 'number',
//       },
//       { field: 'grade', headerName: 'Grade', ...commonColumnProps },
//       { field: 'workOrder', headerName: 'workOrder', ...commonColumnProps },
//       {
//         field: 'project',
//         headerName: 'Project',
//         ...commonColumnProps,
//         type: 'singleSelect',
//         valueOptions: projects,
//       },
//       {
//         field: 'load',
//         headerName: 'Load',
//         ...commonColumnProps,
//         type: 'singleSelect',
//         valueOptions: loads,
//       },
//       {
//         field: 'warehouse',
//         headerName: 'Warehouse',
//         ...commonColumnProps,
//         type: 'singleSelect',
//         valueOptions: warehouses,
//       },
//       {
//         field: 'dateReceived',
//         headerName: 'Received',
//         ...commonColumnProps,
//         ...dateCell(),
//       },
//       // { field: 'location', headerName: 'location', ...commonColumnProps, type: 'singleSelect',  valueOptions: locations },
//       // { field: 'assetComment', headerName: 'assetComment', ...commonColumnProps },
//       // { field: 'palletNo', headerName: 'palletNo', ...commonColumnProps, type: 'number' },
//       // { field: 'r2Grade', headerName: 'r2Grade', ...commonColumnProps },
//       // { field: 'modified', headerName: 'modified', ...commonColumnProps, type: 'boolean' },
//     ],

//     vendors: [
//       {
//         field: 'vendorId',
//         headerName: 'VendorId',
//         ...commonColumnProps,
//         type: 'number',
//       },
//       { field: 'vendorName', headerName: 'Vendor', ...commonColumnProps },
//       { field: 'contactNumber', headerName: 'Contact', ...commonColumnProps },
//       { field: 'suburb', headerName: 'Suburb', ...commonColumnProps },
//       { field: 'state', headerName: 'State', ...commonColumnProps },
//       { field: 'country', headerName: 'Country', ...commonColumnProps },
//       { field: 'postcode', headerName: 'Postcode', ...commonColumnProps },
//       { field: 'abn', headerName: 'ABN', ...commonColumnProps },
//       {
//         field: 'bankName',
//         headerName: 'BankName',
//         ...commonColumnProps,
//       },
//       {
//         field: 'bankAccountNumber',
//         headerName: 'AccountNumber',
//         ...commonColumnProps,
//       },
//       {
//         field: 'paymentTerms',
//         headerName: 'PaymentTerms',
//         ...commonColumnProps,
//       },
//       {
//         field: 'lastPurchaseDate',
//         headerName: 'LastPurchase',
//         ...commonColumnProps,
//         ...dateCell(),
//       },
//       {
//         field: 'lastPaymentDate',
//         headerName: 'LastPayment',
//         ...commonColumnProps,
//         ...dateCell(),
//       },
//       {
//         field: 'isPreferredVendor',
//         headerName: 'PreferredVendor',
//         ...commonColumnProps,
//         type: 'boolean',
//       },
//       {
//         field: 'isActive',
//         headerName: 'isActive',
//         ...commonColumnProps,
//         type: 'boolean',
//       },
//     ],
//     quotes: [
//       {
//         field: 'quoteID',
//         headerName: 'quoteID',
//         ...commonColumnProps,
//       },
//       // { field: 'customerID', headerName: 'Vendor', ...commonColumnProps },
//       {
//         field: 'customerContactPersonName',
//         headerName: 'ContactPerson',
//         ...commonColumnProps,
//       },
//       { field: 'customerPhone', headerName: 'Phone', ...commonColumnProps },
//       { field: 'customerEmail', headerName: 'Email', ...commonColumnProps },
//       { field: 'customerAddress', headerName: 'Address', ...commonColumnProps },
//       { field: 'customerCity', headerName: 'City', ...commonColumnProps },
//       { field: 'customerCountry', headerName: 'Country', ...commonColumnProps },
//       { field: 'customerState', headerName: 'State', ...commonColumnProps },
//       {
//         field: 'customerZipCode',
//         headerName: 'PostCode',
//         ...commonColumnProps,
//       },
//       {
//         field: 'quoteDate',
//         headerName: 'QuoteDate',
//         ...commonColumnProps,
//         ...dateCell(),
//       },
//       {
//         field: 'quoteExpiryDate',
//         headerName: 'ExpiryDate',
//         ...commonColumnProps,
//         ...dateCell(),
//       },
//       { field: 'salesPerson', headerName: 'SalesPerson', ...commonColumnProps },
//       { field: 'poNumber', headerName: 'PONumber', ...commonColumnProps },
//       { field: 'quantity', headerName: 'Quantity', ...commonColumnProps },
//       // { field: 'description', headerName: 'LastPayment', ...commonColumnProps, ...dateCell() },
//       { field: 'quoteType', headerName: 'QuoteType', ...commonColumnProps },
//       //{ field: 'unitPrice', headerName: 'isActive', ...commonColumnProps, type: 'boolean' },
//       // { field: 'taxes', headerName: 'LastPayment', ...commonColumnProps, ...dateCell() },
//       { field: 'totalAmount', headerName: 'TotalAmount', ...commonColumnProps },
//       // { field: 'paymentMethod', headerName: 'isActive', ...commonColumnProps, type: 'boolean' },
//       // { field: 'currency', headerName: 'isActive', ...commonColumnProps, type: 'boolean' },
//       // { field: 'discount', headerName: 'isActive', ...commonColumnProps, type: 'boolean' },
//       // { field: 'shippingMethod', headerName: 'isActive', ...commonColumnProps, type: 'boolean' },
//     ],

//     projectColumns: [
//       { field: 'projectName', headerName: 'Project Name', ...commonColumnProps },
//       { field: 'projectType', headerName: 'Project Type', ...commonColumnProps },
//       { field: 'clientRef', headerName: 'Client Ref', ...commonColumnProps },
//       {
//         field: 'salesManager',
//         headerName: 'Sales Manager',
//         ...commonColumnProps,
//       },
//       {
//         field: 'accountManager',
//         headerName: 'Account Manager',
//         ...commonColumnProps,
//       },
//       {
//         field: 'customer',
//         headerName: 'Customer',
//         ...commonColumnProps,
//       },
//       {
//         field: 'logo',
//         headerName: 'Logo',
//         ...commonColumnProps,
//         align: 'center',
//         headerAlign: 'center',
//         editable: false,
//         renderCell: item => (
//           item?.row?.logo ?
//             <Box
//               p={.3}
//               component='img'
//               src={`data:image/png;base64,${item?.row?.logo || ''}`}
//               sx={{width: '50px', height: '50px'}}
//             />
//           : ''
//         )
//       },
//       {
//         field: 'isActive',
//         headerName: 'Is Active',
//         type: 'boolean',
//         ...commonColumnProps,
//       },
//     ],

//     // accounts: [
//     //   //{ field: 'id', headerName: 'ID', width: 20},
//     //   { field: 'accountId', headerName: 'accountId', ...commonColumnProps },
//     //   { field: 'accountOwner', headerName: 'Account Owner', ...commonColumnProps },
//     //   { field: 'accountName', headerName: 'Account Name', ...commonColumnProps },
//     //   { field: 'accountNumber', headerName: 'Account Number', ...commonColumnProps },
//     //   { field: 'accountType', headerName: 'Account Type', flex: 1, minWidth: 200 },
//     //   { field: 'parentAccount', headerName: 'Parent Account', flex: 1, minWidth: 200 },
//     //   { field: 'email', headerName: 'Email', ...commonColumnProps },
//     //   { field: 'webSite', headerName: 'WebSite', ...commonColumnProps },
//     //   { field: 'industry', headerName: 'Industry', ...commonColumnProps },
//     //   { field: 'rating', headerName: 'Rating', ...commonColumnProps },
//     //   { field: 'employees', headerName: 'Reporting To', ...commonColumnProps },
//     //   { field: 'sicCode', headerName: 'Sic Code', ...commonColumnProps },
//     //   // { field: 'fax', headerName: 'fax', ...commonColumnProps },
//     //   { field: 'tickerSymbol', headerName: 'TickerSymbol', ...commonColumnProps },
//     //   { field: 'ownerShip', headerName: 'OwnerShip', ...commonColumnProps },
//     //   { field: 'annualRevenue', headerName: 'Annual Revenue', ...commonColumnProps },
//     //   { field: 'description', headerName: 'Description', ...commonColumnProps },
//     //   { field: 'phone', headerName: 'Phone', ...commonColumnProps },
//     //   { field: 'billingStreet', headerName: 'BillingStreet', ...commonColumnProps },
//     //   { field: 'billingCity', headerName: 'Billing City', ...commonColumnProps },
//     //   { field: 'billingState', headerName: 'Billing State', ...commonColumnProps },
//     //   { field: 'billingSuburb', headerName: 'Billing Suburb', ...commonColumnProps },
//     //   { field: 'billingPostcode', headerName: 'Billing Postcode', ...commonColumnProps },
//     //   { field: 'billingCountry', headerName: 'Billing Country', ...commonColumnProps },
//     //   { field: 'shippingStreet', headerName: 'Shipping Street', ...commonColumnProps },
//     //   { field: 'shippingCity', headerName: 'Shipping City', ...commonColumnProps },
//     //   { field: 'shippingState', headerName: 'Shipping State', ...commonColumnProps },
//     //   { field: 'shippingSuburb', headerName: 'Shipping Suburb', ...commonColumnProps },
//     //   { field: 'shippingPostcode', headerName: 'Shipping Postcode', ...commonColumnProps },
//     //   { field: 'shippingCountry', headerName: 'Shipping Country', ...commonColumnProps },
//     // ],

//     deals: [
//       //{ field: 'id', headerName: 'ID', width: 20},
//       {
//         field: 'dealId',
//         headerName: 'DealId',
//         ...commonColumnProps,
//         type: 'number',
//       },
//       { field: 'dealOwner', headerName: 'DealOwner', ...commonColumnProps },
//       { field: 'dealName', headerName: 'DealName', ...commonColumnProps },
//       { field: 'dealType', headerName: 'DealType', ...commonColumnProps },
//       { field: 'leadSource', headerName: 'LeadSource', ...commonColumnProps },
//       { field: 'nextStep', headerName: 'NextStep', ...commonColumnProps },
//       { field: 'contactName', headerName: 'ContactName', ...commonColumnProps },
//       {
//         field: 'amount',
//         headerName: 'Amount',
//         ...commonColumnProps,
//         type: 'number',
//       },
//       {
//         field: 'expectedRevenue',
//         headerName: 'ExpectedRevenue',
//         ...commonColumnProps,
//         type: 'number',
//       },
//       { field: 'probability', headerName: 'Probability', ...commonColumnProps },
//       { field: 'stage', headerName: 'Stage', ...commonColumnProps },
//       {
//         field: 'compaignSource',
//         headerName: 'CompaignSource',
//         ...commonColumnProps,
//       },
//       { field: 'description', headerName: 'Description', ...commonColumnProps },
//       {
//         field: 'closingDate',
//         headerName: 'ClosingDate',
//         ...commonColumnProps,
//         ...dateCell(),
//       },
//     ],

//     tasks: [
//       //{ field: 'id', headerName: 'ID', width: 20},
//       {
//         field: 'taskID',
//         headerName: 'Task ID',
//         ...commonColumnProps,
//         editable: false,
//       },
//       { field: 'taskOwner', headerName: 'TaskOwner', ...commonColumnProps },
//       { field: 'subject', headerName: 'Subject', ...commonColumnProps },
//       { field: 'contact', headerName: 'Contact', ...commonColumnProps },
//       { field: 'status', headerName: 'Status', ...commonColumnProps },
//       { field: 'priority', headerName: 'Priority', ...commonColumnProps },
//       { field: 'description', headerName: 'Description', ...commonColumnProps },
//       { field: 'account', headerName: 'Account', ...commonColumnProps },
//       {
//         field: 'accountId',
//         headerName: 'accountId',
//         ...commonColumnProps,
//         type: 'number',
//       },
//       { field: 'dueDate', headerName: 'Due Date', ...commonColumnProps },
//       { field: 'reminder', headerName: 'Reminder', ...commonColumnProps },
//       {
//         field: 'repeat',
//         headerName: 'Repeat',
//         ...commonColumnProps,
//         type: 'boolean',
//       },
//     ],
//     // meetings: [
//     //   //{ field: 'id', headerName: 'ID', width: 20},
//     //   { field: 'meetingId', headerName: 'MeetingId', ...commonColumnProps },
//     //   { field: 'meetingSubject', headerName: 'Meeting Subject', ...commonColumnProps },
//     //   { field: 'meetingLocation', headerName: 'Meeting Location', ...commonColumnProps },
//     //   { field: 'isOnlineMeeting', headerName: 'Online Meeting', ...commonColumnProps },
//     //   { field: 'isAllDay', headerName: 'AllDay', ...commonColumnProps },
//     //   { field: 'meetingStart', headerName: 'Meeting Start', ...commonColumnProps },
//     //   { field: 'meetingEnd', headerName: 'Meeting End', ...commonColumnProps },
//     //   { field: 'meetingHost', headerName: 'Meeting Host', ...commonColumnProps },
//     //   { field: 'meetingParticipants', headerName: 'Meeting Participants', ...commonColumnProps },
//     //   { field: 'reOccuring', headerName: 'ReOccuring', ...commonColumnProps }
//     // ],
//     // calls: [
//     //   //{ field: 'id', headerName: 'ID', width: 20},
//     //   { field: 'callId', headerName: 'callId', ...commonColumnProps },
//     //   { field: 'callSubject', headerName: 'Call Subject', ...commonColumnProps },
//     //   { field: 'callTO', headerName: 'Call TO', ...commonColumnProps },
//     //   { field: 'relatedTO', headerName: 'Related TO', ...commonColumnProps },
//     //   { field: 'callType', headerName: 'Call Type', ...commonColumnProps },
//     //   { field: 'callOutGoingStatus', headerName: 'CallOutGoingStatus', ...commonColumnProps },
//     //   { field: 'callStartTime', headerName: 'CallStartTime', ...commonColumnProps },
//     //   { field: 'callOwner', headerName: 'CallOwner', ...commonColumnProps },
//     //   { field: 'callReminder', headerName: 'CallReminder', ...commonColumnProps },

//     // ],

//     // orders: {
//     //   sales: [
//     //     // { field: 'salesOrderID', headerName: 'Order ID', ...commonColumnProps,},
//     //     {
//     //       field: 'salesOrderNumber',
//     //       headerName: 'Sale Order',
//     //       ...commonColumnProps,
//     //     },
//     //     { field: 'orderRef', headerName: 'Order Ref', ...commonColumnProps },
//     //     // {
//     //     //   field: 'thirdPartyOrderNo',
//     //     //   headerName: 'thirdPartyOrderNo',
//     //     //   ...commonColumnProps,
//     //     //   type: 'number',
//     //     // },
//     //     {
//     //       field: 'orderStatus',
//     //       headerName: 'Status',
//     //       ...commonColumnProps,
//     //       type: 'singleSelect',
//     //       valueOptions: saleOrderStatuses,
//     //     },
//     //     {
//     //       field: 'orderType',
//     //       headerName: 'Type',
//     //       ...commonColumnProps,
//     //       type: 'singleSelect',
//     //       valueOptions: saleOrderTypes,
//     //     },
//     //     // { field: 'firstName', headerName: 'firstName', ...commonColumnProps },
//     //     // { field: 'lastName', headerName: 'lastName', ...commonColumnProps },
//     //     // { field: 'salutation', headerName: 'salutation', ...commonColumnProps },
//     //     // {
//     //     //   field: 'addressLine1',
//     //     //   headerName: 'addressLine1',
//     //     //   ...commonColumnProps,
//     //     // },
//     //     // {
//     //     //   field: 'addressLine2',
//     //     //   headerName: 'addressLine2',
//     //     //   ...commonColumnProps,
//     //     // },
//     //     // { field: 'suburb', headerName: 'suburb', ...commonColumnProps },
//     //     // { field: 'state', headerName: 'state', ...commonColumnProps },
//     //     // { field: 'email', headerName: 'email', ...commonColumnProps },
//     //     // { field: 'postcode', headerName: 'postcode', ...commonColumnProps },
//     //     // {
//     //     //   field: 'mobileNumber',
//     //     //   headerName: 'mobileNumber',
//     //     //   ...commonColumnProps,
//     //     //   type: 'number',
//     //     // },
//     //     // {
//     //     //   field: 'projectId',
//     //     //   headerName: 'projectId',
//     //     //   ...commonColumnProps,
//     //     //   type: 'number',
//     //     // },
//     //     // {
//     //     //   field: 'currency',
//     //     //   headerName: 'Currency',
//     //     //   ...commonColumnProps,
//     //     //   type: 'number',
//     //     // },
//     //     {
//     //       field: 'salesOrderTotal',
//     //       headerName: 'Order Total',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'netTotal',
//     //       headerName: 'Net Total',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     // {
//     //     //   field: 'billing_AddressLine1',
//     //     //   headerName: 'billing_AddressLine1',
//     //     //   ...commonColumnProps,
//     //     // },
//     //     // {
//     //     //   field: 'billing_AddressLine2',
//     //     //   headerName: 'billing_AddressLine2',
//     //     //   ...commonColumnProps,
//     //     // },
//     //     // {
//     //     //   field: 'billing_Suburb',
//     //     //   headerName: 'billing_Suburb',
//     //     //   ...commonColumnProps,
//     //     // },
//     //     // {
//     //     //   field: 'billing_State',
//     //     //   headerName: 'billing_State',
//     //     //   ...commonColumnProps,
//     //     // },
//     //     // {
//     //     //   field: 'billing_Postcode',
//     //     //   headerName: 'billing_Postcode',
//     //     //   ...commonColumnProps,
//     //     // },
//     //     // {
//     //     //   field: 'isBillingAddressDifferent',
//     //     //   headerName: 'isBillingAddressDifferent',
//     //     //   ...commonColumnProps,
//     //     // },
//     //     // {
//     //     {
//     //       field: 'salesOrderDate',
//     //       headerName: 'Order Date',
//     //       ...commonColumnProps,
//     //       ...dateCell(),
//     //     },
//     //   ],
//     //   purchase: [
//     //     //{ field: 'id', headerName: 'ID', width: 20},
//     //     {
//     //       field: 'purchaseOrderNo',
//     //       headerName: 'purchaseOrderNo',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'dateApproved',
//     //       headerName: 'dateApproved',
//     //       ...commonColumnProps,
//     //       ...dateCell(),
//     //     },
//     //     {
//     //       field: 'poTotal',
//     //       headerName: 'poTotal',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'isSelected',
//     //       headerName: 'isSelected',
//     //       ...commonColumnProps,
//     //       type: 'boolean',
//     //     },
//     //     {
//     //       field: 'isExported',
//     //       headerName: 'isExported',
//     //       ...commonColumnProps,
//     //       type: 'boolean',
//     //     },
//     //     {
//     //       field: 'isInactive',
//     //       headerName: 'isInactive',
//     //       ...commonColumnProps,
//     //       type: 'boolean',
//     //     },
//     //     {
//     //       field: 'requestorID',
//     //       headerName: 'requestorID',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'supplierID',
//     //       headerName: 'supplierID',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'purchaseID',
//     //       headerName: 'purchaseID',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'lastUpdated',
//     //       headerName: 'lastUpdated',
//     //       ...commonColumnProps,
//     //       ...dateCell(),
//     //     },
//     //     {
//     //       field: 'lastUpdateUser',
//     //       headerName: 'lastUpdateUser',
//     //       ...commonColumnProps,
//     //     },
//     //     {
//     //       field: 'costCentreID',
//     //       headerName: 'costCentreID',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     { field: 'poType', headerName: 'poType', ...commonColumnProps },
//     //     { field: 'poStatus', headerName: 'poStatus', ...commonColumnProps },
//     //     {
//     //       field: 'requestorComments',
//     //       headerName: 'requestorComments',
//     //       ...commonColumnProps,
//     //     },
//     //     {
//     //       field: 'approverComments',
//     //       headerName: 'approverComments',
//     //       ...commonColumnProps,
//     //     },
//     //     {
//     //       field: 'lastActionedDate',
//     //       headerName: 'lastActionedDate',
//     //       ...commonColumnProps,
//     //       ...dateCell(),
//     //     },
//     //     {
//     //       field: 'supplierInvoiceNo',
//     //       headerName: 'supplierInvoiceNo',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'purchaseOrder_Invoice',
//     //       headerName: 'purchaseOrder_Invoice',
//     //       ...commonColumnProps,
//     //     },
//     //     {
//     //       field: 'purchaseOrder_POAppover',
//     //       headerName: 'purchaseOrder_POAppover',
//     //       ...commonColumnProps,
//     //     },
//     //     {
//     //       field: 'purchaseOrder_Project',
//     //       headerName: 'purchaseOrder_Project',
//     //       ...commonColumnProps,
//     //     },
//     //   ],
//     //   payment: [
//     //     //{ field: 'id', headerName: 'ID', width: 20},
//     //     {
//     //       field: 'purchaseOrderNo',
//     //       headerName: 'purchaseOrderNo',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'dateApproved',
//     //       headerName: 'dateApproved',
//     //       ...commonColumnProps,
//     //       ...dateCell(),
//     //     },
//     //     {
//     //       field: 'poTotal',
//     //       headerName: 'poTotal',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'isSelected',
//     //       headerName: 'isSelected',
//     //       ...commonColumnProps,
//     //       type: 'boolean',
//     //     },
//     //     {
//     //       field: 'isExported',
//     //       headerName: 'isExported',
//     //       ...commonColumnProps,
//     //       type: 'boolean',
//     //     },
//     //     {
//     //       field: 'isInactive',
//     //       headerName: 'isInactive',
//     //       ...commonColumnProps,
//     //       type: 'boolean',
//     //     },
//     //     {
//     //       field: 'requestorID',
//     //       headerName: 'requestorID',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'supplierID',
//     //       headerName: 'supplierID',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'purchaseID',
//     //       headerName: 'purchaseID',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'lastUpdated',
//     //       headerName: 'lastUpdated',
//     //       ...commonColumnProps,
//     //       ...dateCell(),
//     //     },
//     //     {
//     //       field: 'lastUpdateUser',
//     //       headerName: 'lastUpdateUser',
//     //       ...commonColumnProps,
//     //     },
//     //     {
//     //       field: 'costCentreID',
//     //       headerName: 'costCentreID',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     { field: 'poType', headerName: 'poType', ...commonColumnProps },
//     //     { field: 'poStatus', headerName: 'poStatus', ...commonColumnProps },
//     //     {
//     //       field: 'requestorComments',
//     //       headerName: 'requestorComments',
//     //       ...commonColumnProps,
//     //     },
//     //     {
//     //       field: 'approverComments',
//     //       headerName: 'approverComments',
//     //       ...commonColumnProps,
//     //     },
//     //     {
//     //       field: 'lastActionedDate',
//     //       headerName: 'lastActionedDate',
//     //       ...commonColumnProps,
//     //       ...dateCell(),
//     //     },
//     //     {
//     //       field: 'supplierInvoiceNo',
//     //       headerName: 'supplierInvoiceNo',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'purchaseOrder_Invoice',
//     //       headerName: 'purchaseOrder_Invoice',
//     //       ...commonColumnProps,
//     //     },
//     //     {
//     //       field: 'purchaseOrder_POAppover',
//     //       headerName: 'purchaseOrder_POAppover',
//     //       ...commonColumnProps,
//     //     },
//     //     {
//     //       field: 'purchaseOrder_Project',
//     //       headerName: 'purchaseOrder_Project',
//     //       ...commonColumnProps,
//     //     },
//     //   ],

//     //   dispatch: [
//     //     //{ field: 'id', headerName: 'ID', width: 20},
//     //     {
//     //       field: 'dispatchNo',
//     //       headerName: 'dispatchNo',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'dispatchType',
//     //       headerName: 'dispatchType',
//     //       ...commonColumnProps,
//     //     },
//     //     {
//     //       field: 'dispatchedDate',
//     //       headerName: 'dispatchedDate',
//     //       ...commonColumnProps,
//     //       ...dateCell(),
//     //     },
//     //     {
//     //       field: 'pickUpDate',
//     //       headerName: 'pickUpDate',
//     //       ...commonColumnProps,
//     //       ...dateCell(),
//     //     },
//     //     {
//     //       field: 'dispatchMethod',
//     //       headerName: 'dispatchMethod',
//     //       ...commonColumnProps,
//     //     },
//     //     {
//     //       field: 'dispatchUser',
//     //       headerName: 'dispatchUser',
//     //       ...commonColumnProps,
//     //     },
//     //     {
//     //       field: 'consignmentNo',
//     //       headerName: 'consignmentNo',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'containerNo',
//     //       headerName: 'containerNo',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'sealNo',
//     //       headerName: 'sealNo',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'totalWeight',
//     //       headerName: 'totalWeight',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'totalCubicMetres',
//     //       headerName: 'totalCubicMetres',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     // { field: 'comments', headerName: 'comments', ...commonColumnProps },
//     //     { field: 'carrier', headerName: 'carrier', ...commonColumnProps },
//     //     {
//     //       field: 'dispatchStatus',
//     //       headerName: 'dispatchStatus',
//     //       ...commonColumnProps,
//     //     },
//     //     {
//     //       field: 'length',
//     //       headerName: 'length',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'height',
//     //       headerName: 'height',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'width',
//     //       headerName: 'width',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'projectId',
//     //       headerName: 'projectId',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     { field: 'createdBy', headerName: 'createdBy', ...commonColumnProps },
//     //     {
//     //       field: 'created',
//     //       headerName: 'created',
//     //       ...commonColumnProps,
//     //       ...dateCell(),
//     //     },
//     //   ],
//     //   work: [
//     //     //{ field: 'id', headerName: 'ID', width: 20},
//     //     {
//     //       field: 'workOrderNo',
//     //       headerName: 'Work Order',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'workOrderType',
//     //       headerName: 'Work Order Type',
//     //       ...commonColumnProps,
//     //     },
//     //     {
//     //       field: 'workOrderStatus',
//     //       headerName: 'Work Order Status',
//     //       ...commonColumnProps,
//     //     },
//     //     { field: 'account', headerName: 'Account', ...commonColumnProps },
//     //     { field: 'clientRef', headerName: 'Client Ref', ...commonColumnProps },
//     //     { field: 'clientPO', headerName: 'Client PO', ...commonColumnProps },
//     //     {
//     //       field: 'assignedUser',
//     //       headerName: 'Assigned User',
//     //       ...commonColumnProps,
//     //     },
//     //     { field: 'project', headerName: 'Project', ...commonColumnProps },
//     //     {
//     //       field: 'customer',
//     //       headerName: 'Customer',
//     //       ...commonColumnProps,
//     //     },
//     //     {
//     //       field: 'workOrderStartDate',
//     //       headerName: 'Work Order Start Date',
//     //       ...commonColumnProps,
//     //       ...dateCell(),
//     //     },
//     //     // { field: 'workOrderTime', headerName: 'workOrderTime', ...commonColumnProps },
//     //     {
//     //       field: 'workOrderEndDate',
//     //       headerName: 'Work Order End Date',
//     //       ...commonColumnProps,
//     //       ...dateCell(),
//     //     },
//     //     {
//     //       field: 'requestCreated',
//     //       headerName: 'Request Created',
//     //       ...commonColumnProps,
//     //     },
//     //     {
//     //       field: 'orderSource',
//     //       headerName: 'Order Source',
//     //       ...commonColumnProps,
//     //     },
//     //     {
//     //       field: 'contactPerson',
//     //       headerName: 'Contact Person',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //     {
//     //       field: 'mobileNumber',
//     //       headerName: 'Mobile Number',
//     //       ...commonColumnProps,
//     //     },
//     //     { field: 'email', headerName: 'email', ...commonColumnProps },
//     //     { field: 'severity', headerName: 'Severity', ...commonColumnProps },
//     //   ],
//     //   invoice: [
//     //     {
//     //       field: 'invoiceNo',
//     //       headerName: 'Invoice No',
//     //       ...commonColumnProps,
//     //     },
//     //     {
//     //       field: 'invoiceType',
//     //       headerName: 'Invoice Type',
//     //       ...commonColumnProps,
//     //     },
//     //     { field: 'invoiceDate',
//     //       headerName: 'Invoice Date',
//     //       ...commonColumnProps,
//     //       ...dateCell(),
//     //     },
//     //     { field: 'customerPO', headerName: 'CustomerPO', ...commonColumnProps },
//     //     {
//     //       field: 'invoiceStatus',
//     //       headerName: 'Invoice Status',
//     //       ...commonColumnProps,
//     //     },
//     //     {
//     //       field: 'invoiceTotal',
//     //       headerName: 'Invoice Total',
//     //       ...commonColumnProps,
//     //       type: 'number',
//     //     },
//     //   ],
//     // },
//   };
// };

// //Order page
// // export const orderColumns = {
// //   sales: [
// //     //{ field: 'id', headerName: 'ID', width: 20},
// //     {
// //       field: 'salesOrderNumber',
// //       headerName: 'salesOrderNumber',
// //       ...commonColumnProps,
// //     },
// //     { field: 'orderRef', headerName: 'orderRef', ...commonColumnProps },
// //     {
// //       field: 'thirdPartyOrderNo',
// //       headerName: 'thirdPartyOrderNo',
// //       ...commonColumnProps,
// //     },
// //     { field: 'orderStatus', headerName: 'orderStatus', ...commonColumnProps },
// //     { field: 'orderType', headerName: 'orderType', ...commonColumnProps },
// //     { field: 'userId', headerName: 'userId', ...commonColumnProps },
// //     { field: 'firstName', headerName: 'firstName', ...commonColumnProps },
// //     { field: 'lastName', headerName: 'lastName', ...commonColumnProps },
// //     { field: 'salutation', headerName: 'salutation', ...commonColumnProps },
// //     { field: 'addressLine1', headerName: 'addressLine1', ...commonColumnProps },
// //     { field: 'addressLine2', headerName: 'addressLine2', ...commonColumnProps },
// //     { field: 'suburb', headerName: 'suburb', ...commonColumnProps },
// //     { field: 'state', headerName: 'state', ...commonColumnProps },
// //     { field: 'email', headerName: 'email', ...commonColumnProps },
// //   ],
// //   purchase: [
// //     //{ field: 'id', headerName: 'ID', width: 20},
// //     {
// //       field: 'purchaseOrderNo',
// //       headerName: 'purchaseOrderNo',
// //       ...commonColumnProps,
// //     },
// //     { field: 'dateApproved', headerName: 'dateApproved', ...commonColumnProps },
// //     { field: 'poTotal', headerName: 'poTotal', ...commonColumnProps },
// //     { field: 'isSelected', headerName: 'isSelected', ...commonColumnProps },
// //     { field: 'isExported', headerName: 'isExported', ...commonColumnProps },
// //     { field: 'isInactive', headerName: 'isInactive', ...commonColumnProps },
// //     { field: 'requestorID', headerName: 'requestorID', ...commonColumnProps },
// //     { field: 'supplierID', headerName: 'supplierID', ...commonColumnProps },
// //     { field: 'purchaseID', headerName: 'purchaseID', ...commonColumnProps },
// //     { field: 'lastUpdated', headerName: 'lastUpdated', ...commonColumnProps },
// //     {
// //       field: 'lastUpdateUser',
// //       headerName: 'lastUpdateUser',
// //       ...commonColumnProps,
// //     },
// //   ],
// //   payment: [
// //     //{ field: 'id', headerName: 'ID', width: 20},
// //     {
// //       field: 'purchaseOrderNo',
// //       headerName: 'purchaseOrderNo',
// //       ...commonColumnProps,
// //     },
// //     { field: 'dateApproved', headerName: 'dateApproved', ...commonColumnProps },
// //     { field: 'poTotal', headerName: 'poTotal', ...commonColumnProps },
// //     { field: 'isSelected', headerName: 'isSelected', ...commonColumnProps },
// //     { field: 'isExported', headerName: 'isExported', ...commonColumnProps },
// //     { field: 'isInactive', headerName: 'isInactive', ...commonColumnProps },
// //     { field: 'requestorID', headerName: 'requestorID', ...commonColumnProps },
// //     { field: 'supplierID', headerName: 'supplierID', ...commonColumnProps },
// //     { field: 'purchaseID', headerName: 'purchaseID', ...commonColumnProps },
// //     { field: 'lastUpdated', headerName: 'lastUpdated', ...commonColumnProps },
// //     {
// //       field: 'lastUpdateUser',
// //       headerName: 'lastUpdateUser',
// //       ...commonColumnProps,
// //     },
// //   ],

// //   dispatch: [
// //     //{ field: 'id', headerName: 'ID', width: 20},
// //     { field: 'dispatchNo', headerName: 'dispatchNo', ...commonColumnProps },
// //     { field: 'dispatchType', headerName: 'dispatchType', ...commonColumnProps },
// //     { field: 'dispatchedDate', headerName: 'dispatchedDate', ...commonColumnProps },
// //     { field: 'pickUpDate', headerName: 'pickUpDate', ...commonColumnProps },
// //     {
// //       field: 'dispatchMethod',
// //       headerName: 'dispatchMethod',
// //       ...commonColumnProps,
// //     },
// //     { field: 'dispatchUser', headerName: 'dispatchUser', ...commonColumnProps },
// //     {
// //       field: 'consignmentNo',
// //       headerName: 'consignmentNo',
// //       ...commonColumnProps,
// //     },
// //     { field: 'containerNo', headerName: 'containerNo', ...commonColumnProps },
// //     { field: 'sealNo', headerName: 'sealNo', ...commonColumnProps },
// //     { field: 'totalWeight', headerName: 'totalWeight', ...commonColumnProps },
// //     {
// //       field: 'totalCubicMetres',
// //       headerName: 'totalCubicMetres',
// //       ...commonColumnProps,
// //     },
// //     { field: 'comments', headerName: 'comments', ...commonColumnProps },
// //     { field: 'carrier', headerName: 'carrier', ...commonColumnProps },
// //     {
// //       field: 'dispatchStatus',
// //       headerName: 'dispatchStatus',
// //       ...commonColumnProps,
// //     },
// //   ],
// //   work: [
// //     //{ field: 'id', headerName: 'ID', width: 20},
// //     { field: 'workOrderID', headerName: 'workOrderID', ...commonColumnProps },
// //     { field: 'workOrderNo', headerName: 'workOrderID', ...commonColumnProps },
// //     {
// //       field: 'workOrderType',
// //       headerName: 'workOrderType',
// //       ...commonColumnProps,
// //     },
// //     { field: 'clientRef', headerName: 'clientRef', ...commonColumnProps },
// //     { field: 'clientPO', headerName: 'clientPO', ...commonColumnProps },
// //     { field: 'dateRaised', headerName: 'dateRaised', ...commonColumnProps },
// //     { field: 'sla', headerName: 'sla', ...commonColumnProps },
// //     { field: 'dateSigned', headerName: 'dateSigned', ...commonColumnProps },
// //     {
// //       field: 'workOrderDate',
// //       headerName: 'workOrderDate',
// //       ...commonColumnProps,
// //     },
// //     {
// //       field: 'workOrderTime',
// //       headerName: 'workOrderTime',
// //       ...commonColumnProps,
// //     },
// //     {
// //       field: 'dateCompleted',
// //       headerName: 'dateCompleted',
// //       ...commonColumnProps,
// //     },
// //     {
// //       field: 'opportunityNumber',
// //       headerName: 'opportunityNumber',
// //       ...commonColumnProps,
// //     },
// //     { field: 'orderSource', headerName: 'orderSource', ...commonColumnProps },
// //     {
// //       field: 'workOrderInstructions',
// //       headerName: 'workOrderInstructions',
// //       ...commonColumnProps,
// //     },
// //   ],
// // };

// //Home page
// export const homeColumns = {
//   leads: [
//     //{ field: 'id', headerName: 'ID', width: 20},
//     { field: 'leadOwner', headerName: 'Lead owner', ...commonColumnProps },
//     { field: 'leadName', headerName: 'Lead name', ...commonColumnProps },
//     { field: 'firstName', headerName: 'First name', ...commonColumnProps },
//     { field: 'lastName', headerName: 'Last name', ...commonColumnProps },
//     { field: 'leadStatus', headerName: 'Lead status', ...commonColumnProps },
//     { field: 'email', headerName: 'Email', flex: 1, minWidth: 200 },
//   ],
//   deals: [
//     //{ field: 'id', headerName: 'ID', width: 20},
//     {
//       field: 'dealId',
//       headerName: 'DealId',
//       ...commonColumnProps,
//     },
//     { field: 'dealOwner', headerName: 'DealOwner', ...commonColumnProps },
//     { field: 'dealName', headerName: 'DealName', ...commonColumnProps },
//     { field: 'dealType', headerName: 'DealType', ...commonColumnProps },
//     // { field: 'leadSource', headerName: 'LeadSource', ...commonColumnProps },
//     // { field: 'nextStep', headerName: 'NextStep', ...commonColumnProps },
//     { field: 'contactName', headerName: 'ContactName', ...commonColumnProps },
//     {
//       field: 'amount',
//       headerName: 'Amount',
//       ...commonColumnProps,
//       type: 'number',
//     },
//     // { field: 'expectedRevenue', headerName: 'ExpectedRevenue', ...commonColumnProps, type: 'number' },
//     // { field: 'probability', headerName: 'Probability', ...commonColumnProps },
//     { field: 'stage', headerName: 'Stage', ...commonColumnProps },
//     // { field: 'compaignSource', headerName: 'CompaignSource', ...commonColumnProps },
//     // { field: 'description', headerName: 'Description', ...commonColumnProps },
//     {
//       field: 'closingDate',
//       headerName: 'ClosingDate',
//       ...commonColumnProps,
//       ...dateCell(),
//     },
//   ],
//   tasks: [
//     //{ field: 'id', headerName: 'ID', width: 20},
//     {
//       field: 'taskID',
//       headerName: 'Task ID',
//       ...commonColumnProps,
//     },
//     { field: 'taskOwner', headerName: 'TaskOwner', ...commonColumnProps },
//     { field: 'subject', headerName: 'Subject', ...commonColumnProps },
//     { field: 'contact', headerName: 'Contact', ...commonColumnProps },
//     { field: 'status', headerName: 'Status', ...commonColumnProps },
//     { field: 'priority', headerName: 'Priority', ...commonColumnProps },
//     // { field: 'description', headerName: 'Description', ...commonColumnProps },
//     { field: 'account', headerName: 'Account', ...commonColumnProps },
//     // { field: 'accountId', headerName: 'accountId', ...commonColumnProps, type: 'number' },
//     // { field: 'dueDate', headerName: 'Due Date', ...commonColumnProps },
//     // { field: 'reminder', headerName: 'Reminder', ...commonColumnProps },
//     // { field: 'repeat', headerName: 'Repeat', ...commonColumnProps, type: 'boolean' },
//   ],
//   assets: [
//     //{ field: 'id', headerName: 'ID', width: 20},
//     { field: 'ssn', headerName: 'SSN', ...commonColumnProps, type: 'number' },
//     { field: 'make', headerName: 'Make', ...commonColumnProps },
//     { field: 'model', headerName: 'Model', ...commonColumnProps },
//     { field: 'serialNo', headerName: 'Serial No', ...commonColumnProps },
//     { field: 'barcode', headerName: 'Barcode', ...commonColumnProps },
//     {
//       field: 'buyPrice',
//       headerName: 'Buy Price',
//       ...commonColumnProps,
//     },
//     {
//       field: 'sellPrice',
//       headerName: 'sell Price',
//       ...commonColumnProps,
//       type: 'number',
//     },
//   ],
// };
